AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Allow longer blocks in tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
# Allow longer methods for specific cases
Metrics/MethodLength:
  Max: 15

# Allow missing documentation for now
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
